server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth-service
          uri: lb://ead-user-auth-service
          predicates:
            - Path=/ead-user-auth/**

        - id: course-service
          uri: lb://ead-course-service
          predicates:
            - Path=/ead-course/**

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}
  instance:
    hostname: localhost