server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth-service
          uri: 'http://localhost:8087'
          predicates:
            - Path=/ead-user-auth/**

        - id: course-service
          uri: 'http://localhost:8082'
          predicates:
            - Path=/ead-course/**